### PR TITLE
Login and signup design

### LINKED ISSUE #43: Login and sign up ignore our template

### LINKED ISSUE #45: Signup design

### PR DESCRIPTION
**Pull request by AmirSavand**
# Issues

- [x] Resolves #43 
- [x] Resolves #45

# Screenshots

### Clean

image

### With error

image

### Clean

image

### With error

image

## New font

image

## New background for sign up and login

image

## New design

image

### CODE REVIEW

**Comment by AmirSavand** [comment]
I did override it but it didn't work at all.
Do this when you can no rush.

**Comment by Alir3z4** [comment]
@AmirSavand is says you have to override `account/login.html` template

> For instance, the view corresponding to the account_login URL uses the template account/login.html. If you create a file with this name in your code layout, it can override the one shipped with allauth. -- https://django-allauth.readthedocs.io/en/latest/templates.html#overridable-templates

**Comment by AmirSavand** [comment]
I found that `registration/login.html` will do the trick, ok I will try `account/login.html`.

**Comment by Alir3z4** [comment]
registration/login.html is useful when using django-registration app.
We're using Django Allauth and that uses different location.
You can just remove registration/login.html file completely

**Comment by AmirSavand** [comment]
@Alir3z4 how to modify `/accounts/confirm-email/` template?

**Comment by Alir3z4** [comment]
> @Alir3z4 how to modify /accounts/confirm-email/ template?

This should be in the documentation as well.
Check the docs and let let me know

However, we can do that later right ?
If this pull request is ready, let's merge and move on

**Comment by AmirSavand** [comment]
I checked the github repo, I changed the template name, tried many things but didn't work, I think it should be set.

Anyway, I will ignore it for now, and make this ready to merge soon.

**Comment by Alir3z4** [comment]
The design is really nice.
Great job on this.

**Comment by Alir3z4** [comment]
by the way you may find them at https://django-allauth.readthedocs.io/en/latest/advanced.html#sending-email

**Comment by AmirSavand** [comment]
image

@Alir3z4 no the design was just plain bootstrap 4, here's a simple modification (10 lines of css)

**Comment by AmirSavand** [comment]
@Alir3z4 this pull request is ready to be merged.

**Comment by Alir3z4** [comment]
Nice and dice <3
Lovely

**Comment by Alir3z4** [comment]
Great job.
I've merged
Will see how it is on the staging server.

keep up the great work!

**Pull request merged**
