### PR TITLE
Fixes #33: message formating

### LINKED ISSUE #33: Add message formats
- [ ] Turn links into `<a>`

### PR DESCRIPTION
**Pull request by Alir3z4**
Fixes #33

### CODE REVIEW

**Comment by AmirSavand** [comment]
Wooo

**Comment by Alir3z4** [comment]
@AmirSavand does Angular let the messages to render in safe ? I mean rendering html data ?

**Comment by AmirSavand** [comment]
I have to configure it.

**Comment by Alir3z4** [comment]
> I have to configure it.

Should we take care of it in this pull request or another ?

**Comment by AmirSavand** [comment]
Another pull.

**Comment by AmirSavand** [comment]
What about other converts? Like quote? or code?

**Comment by Alir3z4** [comment]
I see
I think this is not an efficient way.
This can be done via https://github.com/SavandBros/whisper/issues/48 way better.

**Comment by AmirSavand** [comment]
Good call.

**Pull request closed without merging**
