### PR TITLE
Update

### PR DESCRIPTION
**Pull request by AmirSavand**

### CODE REVIEW

**Comment by Alir3z4** [comment]
Nice <3

**Comment by Alir3z4** [comment]
This is good so far.
Once this is merged, I will add some tiny new changes.
When do you think this will be ready?

**Comment by AmirSavand** [comment]
Let me do a proper design update and use angularjs for handling socket and it's ready.

Today ❤️

**Comment by Alir3z4** [comment]
Thanks for letting me know.
I'll be working on the REST endpoint you wanted as well.

**Comment by AmirSavand** [comment]
What about giving `JSON` data to views? That way we won't do any requests.

I think you already meant that.

**Comment by Alir3z4** [comment]
You mean making a JSON string inside the request.
You want list of Rooms, correct ?

**Comment by AmirSavand** [comment]
Yes I want the `Rooms` as a `JSON` string. Check this out:

```
{{ rooms }} // This outputs a JSON string instead of queryset object
```

**Comment by Alir3z4** [comment]
Okay, I got it,
Will make it happen quick now

**Comment by AmirSavand** [comment]
This is ready for merge.

**Comment by Alir3z4** [comment]
Nice!

**Pull request merged**
